version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "RBniCS/RBniCSx/.github/workflows/ci.yml"
      - dependency-name: "RBniCS/RBniCSx/.github/workflows/ci_unversioned_only.yml"
